### ISSUE TITLE
Students can place a resistor on the breadboard

### ISSUE THREAD

**Issue by randyfortier** [Breadboard-Lab/BreadboardLab#12]
Configuration parameters:

- Resistance (e.g. 220Ω)
- Wattage (e.g. 0.16W)
- Error (e.g. ±5%)
- Band colours (e.g. Red, Red, Brown, Gold)
- Base colour (e.g. Beige)

**Comment by SethCohen** [comment]
Closed with a98a52b3f6424ef5cecbe0bae2f09a37e1a98dc2
